name: Compile Latex

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document with pre/post compile actions
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv.tex
          latexmk_use_xelatex: true
          working_directory: /
          pre_compile: |
            rm cv.pdf
          post_compile: |
            ls cv.pdf
      - uses: actions/upload-artifact@v2
        with:
          name: CV
          path: cv.pdf