name: Compile Latex

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::Build_$(date +"%Y.%m.%d_%H-%M")"
      - name: Set up Git repo
        uses: actions/checkout@v2
      - name: Compile CV
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv.tex
          latexmk_use_xelatex: true
          working_directory:
          post_compile: |
            mv cv.pdf cv-${{ steps.date.outputs.date }}.pdf
      - uses: actions/upload-artifact@v2
        with:
          name: CV
          path: cv.pdf
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: cv.pdf
